### ISSUE TITLE
sdmData: use independent test data

### ISSUE THREAD

**Issue by samuelbosch** [babaknaimi/sdm#1]
Hi,

I tried to use the sdm R package but I'm unable to provide independent test data. The test parameter is specified in the documentation but when I pass my data R fails to find the correct inherited method.
My parameters are:
formula = Occurrence~coords(longitude+latitude)
train = data.frame with coordinates
test = data.frame with coordinates
predictors = RasterStack

Is there a place where I can contribute to the R package ?

Best,

Samuel

**Comment by babaknaimi** [comment]
Hi Samuel,

I am not sure if you get this issue fixed, but if not, you need to convert your data into SpatialPointsDataFrame when you have Raster* object. In future versions, I make it also possible to have data.frame with coordinates working with Raster* object.

Best,
Babak

**Comment by samuelbosch** [comment]
Hi Babak,

I used another sdm package and have since then graduated :-).

Best,

Samuel
