### ISSUE TITLE
parallelSettings parameter in sdm(formula, data, methods, parallelSettings) always falls back to ncore = 1

### ISSUE THREAD

**Issue by RWunderlich** [babaknaimi/sdm#13]
I tried a range of combinations and also defining clusters outside of the _sdm_ command.
No combination of ncore (tried values between 2 and 12 on a 16 core cpu), method (tried both "parallel" and "foreach"), and fork (tried both T and F) works.

Any suggestions what might be going on?

**Comment by RWunderlich** [comment]
more details

I **does work** for a single algorithm or a few algorithms at a time (for a single species) **but not for more than 13 algorithms** (i need 27 in my case) when **using any number of subsampling replicate models** (i tried 11 down to 2 replicates).

**Comment by babaknaimi** [comment]
Can you share the code (and more information that may help to understand the situation) please?

**Comment by RWunderlich** [comment]
thx for getting back.

mymethods <- c("brt", "cart", "cart", ...., "method26", method27")

**This does work but ncore is reset to 1:**
themodel <- sdm(formula = P~V1+V2+V3, data = data, methods = mymethods, replication = "sub", n = 5, test.percent=25, parallelSettings = list(ncore = 5, method = "parallel"))

**This does works:**
themodel <- sdm(formula = P~V1+V2+V3, data = data, methods = mymethods[1:13], replication = "sub", n = 5, test.percent=25,
parallelSettings = list(ncore = 5, method = "parallel"))
**But this does not:**
themodel <- sdm(formula = P~V1+V2+V3, data = data, methods = mymethods[13:25], replication = "sub", n = 5, test.percent=25,
parallelSettings = list(ncore = 5, method = "parallel"))

**Temporary solution:**
themodel <- list()
for (i in 1:27) {
  themodel[[i]] <- sdm(formula = P~V1+V2+V3, data = data, methods = mymethods[i], replication = "sub", n = 5, test.percent=25,
  parallelSettings = list(ncore = 5, method = "parallel"))
}

**The latter pseudo code completes with (apparently) correct results (100% success) despite printing an error:**
Error in serialize(data, node$con) : error writing to connection

**Comment by RWunderlich** [comment]
I found the solution:
The issue was the maxent algorithm, in my case no. 14.
So if I use ifelse(i == 14, 1, 5) as the value of ncore everything is fine!
