### ISSUE TITLE
Error in o[[id[j]]] : subscript out of bounds #for predict function

### ISSUE THREAD

**Issue by ratneshkarjee** [babaknaimi/sdm#22]
Dear @babaknaimi ,
I would like to thank you for this wonderful package. This package really helped everyone to run SDM by replicating those available codes. However, now a day, I am facing an issue with the 'predict' function. I ran each model and observed that only  maxent having some issue as a result I am getting the error. Please help me to solve this issue. 

Thanks 
with regards
Ratnesh

I am using the following codes:
# Fit model
modcur <- sdm(species~., disCUR, methods = c('glm', 'brt', 'rf', 'maxent'), 
              replication =  'cv', n= 10, cv.folds=5, 
              parallelSettings = list(ncore =16, method = 'parallel'))

# predict model [getting error]
pred <- predict(modcur, biocur, nc=16)

Error in o[[id[j]]] : subscript out of bounds

**Comment by ben-0494** [comment]
Is your problem solved, i am facing the same problem
