### ISSUE TITLE
Predict model issues 

### ISSUE THREAD

**Issue by kamelgithub** [babaknaimi/sdm#25]
Good evening 
I do have a little issue while running predict function for my sdm model, I get this following error message 
"Predict the number of values returned by the predict does not match the number of cells in new data! "

When I use res=10, res=5, res=2.5 it's all good, but the issue is when I have downloaded the 0.5 resolution
Please, I need help

**Comment by Wycology** [comment]
@kamelgithub, the issue has been resolved in sdm version 1.2.40, update your version.

**Comment by kamelgithub** [comment]
Thank you for your response
