### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by SDMENM** [babaknaimi/sdm#3]
Hello Babak, 

When I run predict function, I get the following message.
p1<-predict(m, projection, filename='pr.img')
Error in .generateWLP(x = object, newdata = newdata, w = w, species = species,  : 
  the data does not contain some or all of the variables that the model needs...

I couldn't figured it out, where am I making mistake?

**Comment by babaknaimi** [comment]
Please check the name of the predictor variables ("projection" in your code) and compare with the name of the predictors used to fit SDMs. This error suggests that at least one of the required variables does not exist in "projection" dataset.

**Comment by SDMENM** [comment]
Thank you Babak, it helped.
