### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by mahm1991** [babaknaimi/sdm#6]
![Capture](https://user-images.githubusercontent.com/53847897/121741148-ae6a4180-cb30-11eb-8e48-bb91609da3ab.JPG)

Hye Babak Naimi,

I tried to run UI, but this error occurred. hope you can help me

**Comment by babaknaimi** [comment]
Do you have all the required packages installed?

You can try installAll() to get all the required packages installed on your machine.

**Comment by mahm1991** [comment]
Solved, thank mr babak
