### ISSUE TITLE
SpatialPointsDataFrame and RasterStack have same geospatial projection but erroneous plotting 

### ISSUE THREAD

**Issue by kamaulindhardt** [babaknaimi/sdm#7]
Dear SDM team,
and other enthusiasts,

Thank you for making this package available and accessible through detailed tutorials and training. Especially Babak Naimi and Migual B. Araujo that have provided a thorough screencast on SDM, see here https://www.youtube.com/watch?v=TAbXwEEV56I 

I am completely exhausted from surfing the internet on ways of solving my issue encountered with my own data, when following Babak Naimi (https://github.com/babaknaimi) and Migual B. Araujo example on Youtube. 

For some reason, I cannot align my observation points from my SpatialPointsDataFrame to the map generated from the BioClim RasterStack, see screenshot below.

<img width="875" alt="image" src="https://user-images.githubusercontent.com/83076278/125650755-3f6a219a-2683-440e-bd83-134e16d3f9f8.png">

![image](https://user-images.githubusercontent.com/83076278/125651098-4dbadc94-9d8b-4757-a348-78da65e8429c.png)

I need to have the points moved south-eastwards. I have tried setting the coordinate reference system (crs) to the same for each of the objects, but no luck when plotting, even though they apparently have similar crs settings. 

Please help if you have any suggestions on how to go around this issue by perhaps using an alternative function to load in the observations etc.. 

Here is my code:

```
# TRYOUT WITH sdm package

# Libraries
library(tidyverse)
library(tidymodels)
library(sdm)
library(dismo)
library(dplyr)
library(mapview)
library(raster)
library(usdm)
library(rgdal)

# Reading data
era.af <- read_csv("era.af_modeling_df_CLEAN.csv")

class(era.af)

as.data.frame(era.af)

class(era.af)


dim(era.af)

table(era.af$PrName.Code)


era.af.sp <- era.af %>%
  dplyr::select(Latitude, Longitude)

era.af.sp$type <- 1

era.af.sp %>%
  drop_na()


coordinates(era.af.sp) <- c("Latitude", "Longitude")
projection(era.af.sp) <- '+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0'
class(era.af.sp)
crs(era.af.sp)


# Download bioclim variables

bio <- raster::getData('worldclim', var='bio', res=10)
class(bio)
crs(bio)

# reproject data crs
era.af.sp <- sp::spTransform(era.af.sp, CRSobj = crs(bio))

plot(bio[[1]])
points(era.af.sp)
```

**Comment by babaknaimi** [comment]
Hi,
Sometimes, such misplacing is a plot visualization issue and the data is OK. It usually happens when you change the size of the plot window, so please make sure if that is not the case. You may use mapview to check:

library(mapview)
mapview(bio[[1]]) + mapview(era.af.sp)

#-----
If it is not the source of the issue, it would seem that the points are subjected to the locational error or a wrong crs is assigned to the dataset

**Comment by kamaulindhardt** [comment]
Thank you @babaknaimi for your comment on this. I actually found out that the issue was related to 

`coordinates(era.af.sp) <- c("Longitude", "Latitude")` that whould be changed to `coordinates(era.af.sp) <- c("Latitude", "Longitude")` Now it worked fine.
